title: Akafael
description: > # this means to ignore newlines until "baseurl:"
  This is collection of bit from myself made with love and code
  using Jekyll and hosted on Github. It compress all sort of things
  from programming snippets to produtivity tips. My journal it is!
  Feel free to dig it for anything useful for you.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Rafael Lima # add your name
#author-img: david-freeman.jpg # add your photo
about-author: I am a mechatronics engineering student. Always hungry to keep learning. # add description
social-twitter: akafael # add your Twitter handle
social-facebook: akafael  # add your Facebook handle
social-github: akafael # add your Github handle
social-linkedin: akafael # add your Linkedin handle
social-email:  # add your Email address

# Disqus
discus-identifier: akafael # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
